version: 1
ingress:
    - className: platform
      network: public
otomi:
    hasExternalDNS: false
    hasExternalIDP: false
    hasCloudLB: false
    isHomeMonitored: false
    isManaged: false
    isMultitenant: true
    version: latest
