apiVersion: v2
appVersion: v2.2.0
dependencies:
- alias: kubeclarity-postgresql
  condition: kubeclarity-postgresql.enabled
  name: postgresql
  repository: https://charts.bitnami.com/bitnami
  version: 10.12.2
description: Charts for KubeClarity deployment.
home: https://github.com/openclarity/kubeclarity
icon: https://github.com/openclarity/kubeclarity/raw/main/images/kubeclarity-logo.png
maintainers:
- name: KubeClarity
  url: https://github.com/openclarity/kubeclarity
name: kubeclarity
sources:
- https://github.com/openclarity/kubeclarity
type: application
version: v2.2.0
