# this release file is used to dump only the user input used by helmfile, which are found in the values repo files
# so no defaults or derived values are dumped!!
bases:
  - ../helmfile.d/snippets/env.gotmpl
---
{{- $v := .Values }}

releases:
  - name: dump
    # Never change 'installed' flag to true as you do not want to see release being deployed
    installed: false
    chart: ../charts/raw
