bases:
  - snippets/defaults.yaml
---
bases:
  - snippets/env.gotmpl
---
bases:
  - snippets/derived.gotmpl
---
{{ readFile "snippets/templates.gotmpl" }}
{{- $v := .Values }}
{{- $c := $v.charts }}
{{- $domainSuffix := $v | get "cluster.domainSuffix" nil }}

releases:
  - name: job-certs-aws
    installed:  {{ $c | get "aws-alb-ingress-controller.enabled" }}
    <<: *jobs
    labels:
      group: jobs
      type: cronjob
  - name: job-copy-certs
    installed:  {{ not ($c | get "aws-alb-ingress-controller.enabled") }}
    <<: *jobs
    labels:
      group: jobs
      type: cronjob
  - name: job-gitea-add-users
    installed: {{ and (ne $v.cluster.provider "kind") ($c | get "gitea.enabled" false) }}
    labels:
      pkg: gitea
      group: jobs
      type: cronjob
    <<: *jobs
  - name: job-harbor
    installed: {{ $c | get "harbor.enabled" }}
    labels:
      pkg: harbor
      group: jobs
    <<: *jobs
  - name: job-ingress-azure
    installed: {{ $c | get "ingress-azure.enabled" }}
    <<: *jobs
    labels:
      pkg: ingress-azure
      group: jobs
  - name: host-mods
    installed: {{ $c | get "host-mods.enabled" }}
    namespace: kube-system
    labels:
      pkg: host
    <<: *default
  - name: wait-for-drone
    installed: true
    <<: *wait
    namespace: maintenance
    labels:
      pkg: wait
    values:
      - url: https://drone.{{ $domainSuffix }}
        tasksVersion: {{ $v.versions.tasks }}
        {{- if $v._derived.untrustedCA }}
        customCa: |
          {{- $v._derived.caCert | nindent 10 }}
        {{- end }}
        runPolicy: OnSpecChange

