bases:
  - snippets/defaults.yaml
---
bases:
  - snippets/env.gotmpl
---
bases:
  - snippets/derived.gotmpl
---
{{ readFile "snippets/templates.gotmpl" }}
{{- $v := .Values }}
{{- $c := $v.charts }}

releases:
  - name: aws-ebs-csi-driver
    installed: {{ $c | get "aws-ebs-csi-driver.enabled" }}
    namespace: kube-system
    labels:
      init: true
      pkg: csi
      provider: aws 
    <<: *default
  - name: gatekeeper-operator
    installed: {{ $c | get "gatekeeper-operator.enabled" }}
    namespace: default
    chart: ../charts/gatekeeper-operator
    disableValidationOnInstall: true
    labels:
      pkg: gatekeeper
    values:
      - ../values/gatekeeper/gatekeeper-operator.gotmpl
      - snippets/common.gotmpl
  - name: nginx-ingress-artifacts
    installed: true
    namespace: ingress
    labels:
      tag: ingress
      stage: prep
    <<: *raw
{{- range $index, $ingress := $v.ingress }}
  - name: nginx-ingress-{{ $ingress.className }}
    installed: true
    namespace: ingress
    labels:
      tag: ingress
      stage: prep
      class: {{ $ingress.className }}
      index: {{ $index }}
    missingFileHandler: Debug
    chart: ../charts/nginx-ingress
    values:
      - ../values/nginx-ingress/nginx-ingress.gotmpl
      - snippets/common.gotmpl
{{- end }}
