bases:
  - snippets/defaults.yaml
---
bases:
  - snippets/env.gotmpl
---
bases:
  - snippets/derived.gotmpl
---
{{ readFile "snippets/templates.gotmpl" }}
{{- $v := .Values }}
{{- $c := $v.charts }}

releases:
  - name: job-autoconfig
    {{ if and (eq $v.otomi.hasExternalIDP false) (eq $c.gitea.enabled true) }}
    installed: true
    {{ else }}
    installed: false
    {{ end }}
    <<: *jobs
    labels:
      group: jobs